apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: myapp-db-creds
  namespace: apps
spec:
  vaultAuthRef: vault-auth
  mount: database
  path: creds/myapp-role
  destination:
    name: myapp-db-credentials
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: myapp
  renewalPercent: 67
