apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: myapp-static-secrets
  namespace: apps
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: apps/myapp
  refreshAfter: 30s
  destination:
    name: myapp-api-keys
    create: true
